export enum AppIconsEnum {
  AESTHETICS = 'aesthetics',
  ANGLE_DOWN = 'angle-down',
  ANGLE_LEFT = 'angle-left',
  ANGLE_UP = 'angle-up',
  ANGLE_RIGHT = 'angle-right',
  BAD_HAND = 'bad-hand',
  CALENDAR = 'calendar',
  CIRCLE_CLOSE = 'circle-close',
  CIRCLE_DENIED = 'circle-denied',
  CIRCLE_SUCCESS = 'circle-success',
  CIRCLE_WARNING = 'circle-warning',
  COMMENTS = 'comments',
  GROUP = 'group',
  HEART = 'heart',
  INBOX = 'inbox',
  LOCATION = 'location',
  LOG_OUT = 'logout',
  MAN = 'man',
  NICE_HAND = 'nice-hand',
  NOTIFICATION_ACTIVE = 'notification-active',
  NOTIFICATION = 'notification',
  PAPER = 'paper',
  SEARCH = 'search',
  USER = 'user',
  TRAINE = 'traine',
  WOMAN = 'woman',
}
